on: [push]

jobs:
    fetch:
      runs-on: ubuntu-latest
      name: google fetch
      steps:
        - uses: actions/checkout@v2
        - uses: ./.github/actions/fetch
    slack:
      runs-on: ubuntu-latest
      steps:
        - uses: 8398a7/action-slack@v3
          with:
            status: 'some status'
            fields: all
          env:
            SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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