on: [push]

jobs:
    fetch:
      runs-on: ubuntu-latest
      name: google fetch
      steps:
        - uses: actions/checkout@v2
        - uses: ./.github/actions/fetch
        - uses: ./.github/actions/slack-notifications
          with:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
            MESSAGE: 'testing'