on: [push]

jobs:
    fetch:
      runs-on: ubuntu-latest
      continue-on-error: ${{ true }}
      name: google fetch
      steps:
        - uses: actions/checkout@v2
        - uses: ./.github/actions/fetch
    failed-job:
      runs-on: ubuntu-latest
      continue-on-error: ${{ true }}
      name: job that always fails
      steps:
        - name: exit 1
          run: exit 1
    env-echo:
      runs-on: ubuntu-latest
      if: ${{ true }}
      needs: [fetch, failed-job]
      steps:
        - run: echo ${{ env.GITHUB_REPOSITORY }}
    