on: [push]

jobs:
    successJob:
      runs-on: ubuntu-latest
      name: job that always success
      steps:
        - name: exit 0
          run: exit 0

    failedJob:
      runs-on: ubuntu-latest
      name: job that always fails
      steps:
        - name: exit 1
          run: exit 1

    env_echo:
      runs-on: ubuntu-latest
      if: ${{ always() }}
      needs: [failedJob, successJob]
      steps:
        - run: | 
            echo ${{ needs.successJob.result }}
            echo 'needs.successJob.result: ' ${{ needs.successJob.result == 'success' }}
            echo 'needs.failedJob.result: ' ${{ needs.failedJob.result == 'success' }}
            echo ===
            echo ${{ needs.successJob.result == 'success' && needs.failedJob.result == 'success' }}
            echo ${{ needs.successJob.result == 'failure' || needs.failedJob.result == 'failure' }}
        - name: send DONE
          if: ${{ needs.successJob.result == 'success' && needs.failedJob.result == 'success' }}
          run: |
            echo SUCCESS
        - name: send FAILURE
          if: ${{ needs.successJob.result == 'failure' || needs.failedJob.result == 'failure' }}
          run: |
            echo FAILURE

    