on: [push]

jobs:
    failed-job:
      runs-on: ubuntu-latest
      continue-on-error: ${{ true }}
      name: job that always fails
      steps:
        - name: exit 1
          run: exit 1
    env-echo:
      runs-on: ubuntu-latest
      if: ${{ true }}
      needs: [failed-job]
      steps:
        - run: echo $GITHUB_REPOSITORY && echo $env
    