on: [push]

jobs:
    failedJob:
      runs-on: ubuntu-latest
      continue-on-error: ${{ true }}
      name: job that always fails
      steps:
        - name: exit 1
          run: exit 1
    env_echo:
      runs-on: ubuntu-latest
      if: ${{ true }}
      needs: [failed-job]
      steps:
        - name: send DONE
          if: ${{ needs.failedJob.result != 'failure' }}
          run: |
            echo SUCCESS
        - name: send FAILURE
          if: ${{ needs.failedJob.result == 'failure' }}
          run: |
            echo FAILURE

    